
export const DELETE_RECIPE = 'DELETE_RECIPE';
export const FETCH_RECIPE = 'FETCH_RECIPE';
export const FETCH_NEW_RECIPE = 'FETCH_NEW_RECIPE';
export const SAVE_RECIPE = 'SAVE_RECIPE';
export const CLEAR_RECIPE = 'CLEAR_RECIPE';
export const DELETE_INGREDIENT = 'DELETE_INGREDIENT';
export const ADD_INGREDIENT = 'ADD_INGREDIENT';
export const UPDATE_RECIPES = 'UPDATE_RECIPES';
export const SAVE_NEW_RECIPE = 'SAVE_NEW_RECIPE';
export const UPDATE_SHOPPING_LIST = 'UPDATE_SHOPPING_LIST';
