export const SHOPPING_LIST_ADD_INGREDIENT = 'SHOPPING_LIST_ADD_INGREDIENT';
export const SHOPPING_LIST_DELETE = 'SHOPPING_LIST_DELETE';
export const SHOPPING_LIST_SAVE_INGREDIENT = 'SHOPPING_LIST_SAVE_INGREDIENT';
export const SHOPPING_LIST_CLEAR_FORM = 'SHOPPING_LIST_CLEAR_FORM';
export const SHOPPING_LIST_UPDATE = 'SHOPPING_LIST_UPDATE';
